CREATE TABLE IF NOT EXISTS JH_MEMBER (
  M_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  M_NAME VARCHAR(100),
  M_ID VARCHAR(100) NOT NULL,
  M_PW VARCHAR(255) NOT NULL,
  M_NICKNAME VARCHAR(100),
  M_EMAIL VARCHAR(255),
  M_BIRTH VARCHAR(20),
  M_BIRTH_YN CHAR(1) DEFAULT 'N',
  M_DEL_YN CHAR(1) DEFAULT 'N',
  M_JOIN_COMP_DT DATE,
  M_VACT_CNT DECIMAL(5,1) DEFAULT 0.0,
  PRIMARY KEY (M_SEQ),
  UNIQUE KEY UK_JH_MEMBER_M_ID (M_ID),
  KEY IDX_JH_MEMBER_NICKNAME (M_NICKNAME),
  KEY IDX_JH_MEMBER_EMAIL (M_EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS JH_FILE (
  F_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  F_TYPE VARCHAR(20) NOT NULL,
  F_TYPE_SEQ BIGINT NOT NULL,
  F_OG_NAME VARCHAR(255),
  F_SV_NAME VARCHAR(255),
  F_SIZE BIGINT DEFAULT 0,
  F_MAIN_YN CHAR(1) DEFAULT 'Y',
  F_DEL_YN CHAR(1) DEFAULT 'N',
  PRIMARY KEY (F_SEQ),
  KEY IDX_JH_FILE_TYPE (F_TYPE, F_TYPE_SEQ),
  KEY IDX_JH_FILE_MAIN (F_MAIN_YN, F_DEL_YN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS JH_LETTER (
  L_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  L_SENDER BIGINT NOT NULL,
  L_RECIVER BIGINT NOT NULL,
  L_TITLE VARCHAR(255),
  L_CONTENT TEXT,
  L_SENDT DATETIME DEFAULT CURRENT_TIMESTAMP,
  L_OPEN_YN CHAR(1) DEFAULT 'N',
  L_SENDER_TRASH_STEP INT DEFAULT 0,
  L_RECIVER_TRASH_STEP INT DEFAULT 0,
  L_SENDER_TRASH_DATE DATETIME,
  L_RECIVER_TRASH_DATE DATETIME,
  PRIMARY KEY (L_SEQ),
  KEY IDX_JH_LETTER_SENDER (L_SENDER, L_SENDER_TRASH_STEP),
  KEY IDX_JH_LETTER_RECIVER (L_RECIVER, L_RECIVER_TRASH_STEP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS JH_MAIL_HISTORY (
  HIS_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  M_SEQ BIGINT NOT NULL,
  HIS_AUTH VARCHAR(50),
  HIS_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  HIS_FIND_TYPE VARCHAR(30),
  PRIMARY KEY (HIS_SEQ),
  KEY IDX_JH_MAIL_HISTORY_MEMBER (M_SEQ, HIS_FIND_TYPE, HIS_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS JH_CAL (
  CAL_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  CAL_TYPE VARCHAR(255),
  M_SEQ_MAKE BIGINT,
  M_SEQ_PARTY BIGINT,
  CAL_NAME VARCHAR(255),
  CAL_DEL_YN VARCHAR(255) DEFAULT 'N',
  PRIMARY KEY (CAL_SEQ),
  KEY IDX_JH_CAL_OWNER (CAL_DEL_YN, M_SEQ_MAKE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS JH_CAL_CONT (
  CONT_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  CAL_SEQ BIGINT NOT NULL,
  M_SEQ BIGINT NOT NULL,
  CONT_CONT TEXT,
  CONT_TITLE VARCHAR(255),
  CONT_START_DT DATETIME,
  CONT_END_DT DATETIME,
  CONT_START_TM VARCHAR(20),
  CONT_END_TM VARCHAR(20),
  CONT_DEL_YN VARCHAR(255) DEFAULT 'N',
  CAL_DETAIL_TYPE VARCHAR(255),
  CONT_ALLDAY_YN VARCHAR(255),
  PRIMARY KEY (CONT_SEQ),
  KEY IDX_JH_CAL_CONT_RANGE (CONT_DEL_YN, CAL_SEQ, CONT_START_DT, CONT_END_DT),
  KEY IDX_JH_CAL_CONT_MEMBER (M_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS SAMPLE (
  SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255),
  CONTENT VARCHAR(255),
  REG_DT DATETIME,
  SAMPLE_COLUMN1 VARCHAR(255),
  SAMPLE_COLUMN2 VARCHAR(255),
  TYPE VARCHAR(255),
  DEL_YN VARCHAR(255),
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP PROCEDURE IF EXISTS PROC_UPDATE_VACT_CNT;

DELIMITER //
CREATE PROCEDURE PROC_UPDATE_VACT_CNT(
  IN P_SEQ BIGINT,
  IN P_JOIN_COMP_DT DATE,
  IN P_type VARCHAR(20)
)
BEGIN
  UPDATE JH_MEMBER
  SET M_JOIN_COMP_DT = P_JOIN_COMP_DT,
      M_VACT_CNT = CASE
        WHEN P_JOIN_COMP_DT IS NULL THEN COALESCE(M_VACT_CNT, 0)
        ELSE 15 + GREATEST(TIMESTAMPDIFF(YEAR, P_JOIN_COMP_DT, CURDATE()), 0)
      END
  WHERE M_SEQ = P_SEQ;
END//
DELIMITER ;
